{{- if .Values.serviceMonitor.enabled }}
---
apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: {{ include "livecomments.serviceMonitorName" . }}
  namespace: {{ .Values.serviceMonitor.namespace | default .Release.Namespace }}
  labels:
    {{- include "livecomments.labels" . | nindent 4 }}
    {{- if .Values.serviceMonitor.prometheusReleaseName }}
    release: {{ .Values.serviceMonitor.prometheusReleaseName }}
    {{- end }}
    {{- with .Values.serviceMonitor.labels }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- if .Values.defaultAnnotations }}
  annotations:
    {{- with .Values.defaultAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  selector:
    matchLabels:
      {{- include "livecomments.selectorLabels" . | nindent 6 }}
  {{- if .Values.serviceMonitor.namespaceSelector.any }}
  namespaceSelector:
    any: true
  {{- else if .Values.serviceMonitor.namespaceSelector.matchNames }}
  namespaceSelector:
    matchNames:
      {{- toYaml .Values.serviceMonitor.namespaceSelector.matchNames | nindent 6 }}
  {{- end }}
  endpoints:
    - port: {{ if and .Values.service .Values.service.containerPorts .Values.service.containerPorts.metrics }}{{ .Values.service.containerPorts.metrics.containerPortName }}{{ else }}metrics{{ end }}
      path: {{ .Values.serviceMonitor.path }}
      interval: {{ .Values.serviceMonitor.interval }}
      {{- if .Values.serviceMonitor.scrapeTimeout }}
      scrapeTimeout: {{ .Values.serviceMonitor.scrapeTimeout }}
      {{- end }}
      {{- if .Values.serviceMonitor.honorLabels }}
      honorLabels: {{ .Values.serviceMonitor.honorLabels }}
      {{- end }}
      {{- if .Values.serviceMonitor.metricRelabelings }}
      metricRelabelings:
        {{- toYaml .Values.serviceMonitor.metricRelabelings | nindent 8 }}
      {{- end }}
      {{- if .Values.serviceMonitor.relabelings }}
      relabelings:
        {{- toYaml .Values.serviceMonitor.relabelings | nindent 8 }}
      {{- end }}
{{- end }}
