{{- if and .Values.rbac.create .Values.rbac.role.create }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "heimdall.fullname" . }}-role-binding
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "heimdall.labels" . | nindent 4 }}
  {{- if .Values.defaultAnnotations }}
  annotations:
    {{- with .Values.defaultAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "heimdall.fullname" . }}-role
subjects:
  - kind: ServiceAccount
    name: {{ include "heimdall.serviceAccountName" . }}
    namespace: {{ .Release.Namespace }}
{{- end }}
