{{- if .Values.podDisruptionBudget.enabled }}
---
apiVersion: policy/v1
kind: PodDisruptionBudget
metadata:
  name: {{ include "livechat.pdbName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "livechat.labels" . | nindent 4 }}
  {{- if .Values.defaultAnnotations }}
  annotations:
    {{- with .Values.defaultAnnotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
  {{- end }}
spec:
  {{- if .Values.podDisruptionBudget.minAvailable }}
  minAvailable: {{ .Values.podDisruptionBudget.minAvailable }}
  {{- end }}
  {{- if .Values.podDisruptionBudget.maxUnavailable }}
  maxUnavailable: {{ .Values.podDisruptionBudget.maxUnavailable }}
  {{- end }}
  selector:
    matchLabels:
      {{- include "livechat.selectorLabels" . | nindent 6 }}
{{- end }}
