# VF-Dev3 Namespace Configuration
# Namespace vf-dev3 in Dev01 Cluster
#
# This file contains namespace-specific values for vf-dev3
# Values defined here override cluster and account-level defaults

image:
  tag: "v0.0.1"
