---
apiVersion: v1
kind: Service
metadata:
  name: {{ include "tyrion.serviceName" . }}
  namespace: {{ .Release.Namespace }}
  labels:
    {{- include "tyrion.labels" . | nindent 4 }}
  {{- with .Values.service.annotations }}
  annotations:
    {{- toYaml . | nindent 4 }}
  {{- end }}
spec:
  type: {{ .Values.service.type }}
  ports:
    {{- include "tyrion.servicePorts" . | nindent 4 }}
  selector:
    {{- include "tyrion.selectorLabels" . | nindent 4 }}
